module.exports = class Admin_User {

    EmailTextField = '//input[@name="email"]';
    LoginButton = '//button[@type="submit"]';
    PasswordTextField = '//input[@name="password"]';
    CustomersList = '//div[@class="newsidebar"]';
    PayoutLabel = '//span[@class="header__right__wrap__box__lable" and contains(text(),"Payout")]';
    PayoutValue = '//span[@class="header__right__wrap__box__lable" and contains(text(),"Payout")]//parent::div//span[2]';
    SpentLabel = '//span[@class="header__right__wrap__box__lable" and contains(text(),"Spending")]';
    SpentValue = '//span[@class="header__right__wrap__box__lable" and contains(text(),"Spending")]//parent::div//span[2]';
    EarningsLabel = '//span[@class="header__right__wrap__box__lable" and contains(text(),"Earnings")]';
    EarningsValue = '//span[@class="header__right__wrap__box__lable" and contains(text(),"Earnings")]//parent::div//span[2]';
    PerformanceButton = '//div[@class="pill"]//button//p[contains(text(),"Performance")]';
    CustomerDetails = '//button[@class="pill-button  pill-button-right" and ./p[contains(text(),"Customer Details")]]';
    Calender = '//div[@class="col calendar__wrap"]';
    HeaderOfDashboard = '//div[@class="header"]';
    LogoOnDashboard = '//div[@class="header"]//a//img[@alt="infy-tv-logo"]';
    PayoutsButtonOnDashboard = '//button[@class="button button-secondary" and //button[contains(text(),"Payouts")]]';
    AvailableBalanceOnDashboard = '(//div[@class="header__right__wrap__box tour-balance"])[1]';
    Total_AvailableBalanceOnDashboard = '(//div[@class="header__right__wrap__box tour-balance"])[1]//span[@class="header__right__wrap__box__value"]';
    ProfileBoxOnHeader = '//button[@class="button button-secondary d-flex justify-content-end align-items-center dropdown-toggle btn btn-primary"]';
    NotificationIcon = '//div[@class="position-relative"]';
    HelpIcon = '//div[@class="position-relative"]//parent::div//*[@class="svg-icon"]';
    Search_Icon = '//*[@id="search-btn"]';
    Filter_Icon = '//button[@class="dropdown-toggle btn btn-primary"]';
    LessThen_Icon = '//div[@class="sidebar-row"]//div[@class="sidebar-col toggle ms-1"]//*[@class="svg-icon"]'
    Sort_Icon = "//div[@class='sidebar-row sidebar-row-first']//div[3]//*[name()='svg']";
    GratterThen_Icon = '//div[@class="sidebar-row"]//div[@class="sidebar-col toggle ms-1"]//*[@class="svg-icon"]';
    Invite_Button_in_Customer_Section = '(//button[contains(text(),"Invite")])[1]';
    Invite_Button_on_Dashboard = '(//button[contains(text(),"Invite")])[2]';
    Invite_Popup = '//div[@class="modal-content"]'
    Cancel_Button = '//button[contains(text(),"Cancel")]';
    All_Tab = '//button//p[contains(text(),"All")]';
    Demand_Tab = '//button//p[contains(text(),"Demand")]';
    Publisher_Tab = '//button//p[contains(text(),"Publisher")]';
    First_Customer_Selected = '//div[@class="sidebar-list"]//div[@class="card card-selected"]';
    Performance_Tab = '//button//p[contains(text(),"Performance")]'
    Customer_Details_Tab = '//button//p[contains(text(),"Customer Details")]'
    Selected_Customer_Status = '//div[@class="card card-selected"]//label[@class="card-status"]';
    Collapse_Icon = '(//*[contains(text(),"Collapse")]//parent::*)[1]';
    Expend_Icon = '(//*[contains(text(),"Expand")]//parent::*)[1]';
    Card_Expanded = '//div[@class="card card-selected"]//div[@class="card-expanded"]';
    Customer_LOgo = '//div[@class="card card-selected"]//div[@class=" sb-avatar sb-avatar--src"]';
    Title_Customer_Details = '//h3[contains(text(),"Customer Details")]'
    Customer_Name_On_Card = '//div[@class="card card-selected"]//h6'
    Customer_Name_in_Customer_Details = '(//div[@class="col-12 col-lg-4"]//p)[4]'
    Login_Arrow = '//div[@class="col ps-0 mt-1"]'; 
    Approve_Button = '//button[contains(text(),"Approve")]';
    Official_Email_Id_On_Approval_Form = '//label[contains(text(),"Official Email")]//parent::div//p'
    Title_Of_Company_Name = '(//div[@class="col"])[1]//h2';
    Company_Name_In_Customer_Details = '//label[contains(text(),"Company Name")]//parent::div//p';
    Name_In_Customer_Details = '(//label[contains(text(),"Name")]//parent::div//p)[2]';
    Name_Of_Publisher_In_Customer_Details = '//label[contains(text(),"Name of")]//parent::div//p';
    Website_URL_In_Customer_Details = '//label[contains(text(),"Website URL")]//parent::div//p';
    Pending_Status = '//div[@class="card card-selected"]//label[contains(text(),"Pending")]'
    CustomerSection = '//div[@class="newsidebar"]';
    ProfileName = '//button[@class="button button-secondary d-flex justify-content-end align-items-center dropdown-toggle btn btn-primary"] | //div[@class="tour-settings show dropdown"]';
    ProfileImage = '//button[@class="button button-secondary d-flex justify-content-end align-items-center dropdown-toggle btn btn-primary"]//*';
    UserProfileButton ='//img[@class="rounded-circle ms-2"]/parent::button';
    Finance_Button = "//button[normalize-space()='Finance']";
    SettingOption="//a[normalize-space()='Settings']";
    LabelFirstName="//label[normalize-space()='First Name']";
    LabelLastName="//label[normalize-space()='Last Name']";
    LabelEmail="//label[normalize-space()='Email']";
    LabelPassword="//label[normalize-space()='Password']";
    EmailId="//b[normalize-space()='qatest05@yopmail.com']";
    PasswordChangebutton="//p[@class='profile__main__link fw-lighter']";
    UploadProfilePictureButton="//input[@title='upload profile picture']";
    UploadProfilePictureButtonAfterSelectedphoto="//span[@title='upload profile picture']";
    FirstNameInputBox="//input[@name='profileFirstName']";
    LastNameInputBox="//input[@name='profileLastName']";
    UserEmail = '//label[contains(text(),"Email")]//parent::div[@style="width: fit-content;"]//p//b';
    ChangedProfileName = '//img[@class="rounded-circle ms-2"]/parent::button';
    LinkOfPasswordChange = '//label[contains(text(),"Password")]//parent::div//p[@class="profile__main__link fw-lighter" and contains(text(),"Change")]';
    InviteButton='//button[@class="button button-primary undefined"]';
    InviteButton1='(//button[@class="button button-primary undefined"])[1]';
    InviteButton_On_Users_Setting_Page = '//button[@class="button button-primary undefined" and contains(text(),"Invite")]';
    UsersTab = '//div[@class="col-3 setting-left"]//*[contains(text(),"Users")]';
    SettingsTab = '//a[@class="dropdown-item" and contains(text(),"Settings")]';
    TitleUsers = '//h2[@style="font-weight: 200;" and contains(text(),"Users")]';
    TitleProfile = '//h2[contains(text(),"Profile Settings")]';
    ProfileSettingTitle = '//h2[contains(text(),"Profile Settings")]';
    Remove_Icon = '(//*[contains(text(),"Remove")]//parent::*//parent::p//*)[1]'
    TitleDeleteAUser = '//h2[@style="margin: 10px;" and contains(text(),"Delete a User")]';
    contains = '//tr[@class="i-tr"]';
    QuestaionForCancelOrDelete = '//div[@style="padding: 40px;"]';
    DeleteButton = "//button[contains(text(),'Delete')]";
    ErrorToaster = '//div[@class="Toastify__toast Toastify__toast-theme--light Toastify__toast--error"]';
    CancelButton = "//button[contains(text(),'Cancel')]";
    InvitedUsersName = '(//img[@class=" sb-avatar__image"]//parent::div)[2]//parent::div//p';
    InvitedUsersEmail = '((//img[@class=" sb-avatar__image"]//parent::div)[2]//parent::div//parent::p//parent::div//parent::div[@role="row"]//div[@role="cell"])[2]//p';
    InvitedUsersRole = '(((//img[@class=" sb-avatar__image"]//parent::div)[2]//parent::div//parent::p//parent::div//parent::div[@role="row"]//div[@role="cell"])[3]//p)[2]';
    InvitedUsersStatus = '((//img[@class=" sb-avatar__image"]//parent::div)[2]//parent::div//parent::p//parent::div//parent::div[@role="row"]//div[@role="cell"])[4]//p//p';
    NameBoxOnInviteModal = '//input[@name="name"]';
    PasswordBoxOnInviteModal = '//input[@name="password"]';
    EmailBoxOnInviteModal = '//input[@name="email"]';
    DropdownOfRole = '//select[@name="role"]';
    AdminOption = '//option[@label="Admin"]';
    ManagerOption = '//option[@label="Manager"]';
    EditorOption = '//option[@label="Editor"]';
    LabelPasswordChange = '//label[contains(text(),"Password Change")]';
    CheckboxOfOnFirstLogin = '//input[@type="checkbox"]';
    UserCreated = '//h2[contains(text(),"User Created")]';
    MSGUserHasBeenCreated = '//p[contains(text(),"User has been created.")]';
    DoneButton = "//button[contains(text(),'Done')]";

    NameLabel = '(//th[contains(text(),"Name")])[1]';
    ErrorEnterUserName = '//label[@class="text-input-error-label" and contains(text(),"Enter User Name")]';
    ErrorOfEmail = '//label[@class="text-input-error-label" and contains(text(),"Enter an Email")]';
    EmailLabel = '(//th[contains(text(),"Email")])[1]';
    RoleLabel = '(//th[contains(text(),"Role")])[1]';
    StatusLabel = '(//th[contains(text(),"Status")])[1]';
    JoinedLabel = '(//th[contains(text(),"Joined")])[1]';
    InviteTitle = '//div[@class="modal-header" and ./h2[contains(text(),"Invite")]]';
    NextButton = '//button[@class="button button-primary undefined" and contains(text(),"Next")]';
    LinkOfPasswordChange = '//p[@class="profile__main__link fw-lighter" and contains(text(),"Change")]';
    InpuOfNewPassword = '//input[@placeholder="Enter new Password"]';
    InpuOfConfirmPassword = '//input[@placeholder="Confirm Password"]';
    DisabledSetPasswordButton = '//button[@class="button button-full button-disabled undefined"]';
    EnabledSetPasswordButton = '//button[@class="button button-full button-primary undefined"]';
    ToasterPasswordSuccessfullyChanged = '//div[@class="Toastify__toast Toastify__toast-theme--light Toastify__toast--success"]';
    LogoutTab = '//a[@class="dropdown-item" and contains(text(),"Logout")]';
    FinanceButton="//button[normalize-space()='Finance']";
    InventoryTab="//a[normalize-space()='Inventory']";
    OpenExchangeTabActive="//a[@class='active-link' and contains(text(),'Open Exchange')]";
    PMPDealsTab="//a[normalize-space()='PMP Deals']";
    SearchTitle="//h3[normalize-space()='Search']";
    SelectAllOption="//span[normalize-space()='Select All']";
    IABCategoryTitle="//label[normalize-space()='IAB Category']";
    IABCategoryDropDown="//div[@class='filter__sidebar__filed']//div[@class='dropdown-heading']";
    IABCategoryDropDownSelectAllOption="//span[normalize-space()='Select All']";
    IABCategoryDropDownArtsandEntertainmentOption="//span[normalize-space()='Arts & Entertainment']";
    IABCategoryDropDownHumorOption="//span[normalize-space()='Humor']";
    IABCategoryDropDownSelectAllOptionSelected='//span[contains(text(),"Select All")]/ancestor::label[@class="select-item selected"]';
    IABCategoryDropDownArtsandEntertainmentOptionSelected='//span[contains(text(),"Arts & Entertainment")]/ancestor::label[@class="select-item selected"]';
    IABCategoryDropDownHumorOptionSelected='//span[contains(text(),"Humor")]/ancestor::label[@class="select-item selected"]';
    IABCategoryDropDownBooksLiteratureOptionSelected='//span[contains(text(),"Books & Literature")]/ancestor::label[@class="select-item selected"]';
    IABCategoryDropDownCelebrityFanGossipOptionSelected='//span[contains(text(),"Celebrity Fan/Gossip")]/ancestor::label[@class="select-item selected"]';
    IABCategoryDropDownFineArtOptionSelected='//span[contains(text(),"Fine Art")]/ancestor::label[@class="select-item selected"]';
    DeviceTypeTitle="//label[normalize-space()='Device Type']";
    DeviceTypeTV="//input[@name='deviceTypesTV']";
    DeviceTypeDesktop="//input[@name='deviceTypesDesktop']";
    DeviceTypeMobile="//input[@name='deviceTypesMobile']";
    PlatformTypeTitle="//label[normalize-space()='Platform Type']";
    PlatformTypeOptionCTV="//input[@name='platformTypesCTV']";
    PlatformTypeOptionOTT="//input[@name='platformTypesOTT']";
    PlatformTitle="//label[normalize-space()='Platforms']";
    PlatformDropDown="//body[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[4]/div[1]/div[1]/div[1]/div[1]";
    PlatformDropDownSelectAllOption="//span[normalize-space()='Select All']";
    PlatformDropDownPlatformOption="//span[normalize-space()='platform']";
    PlatformDropDownChromeOSOption="//span[normalize-space()='Chrome OS']";
    PlatformDropDownSelectAllOptionSelected='//span[contains(text(),"Select All")]/ancestor::label[@class="select-item selected"]';
    PlatformDropDownPlatformOptionSelected='//span[contains(text(),"platform")]/ancestor::label[@class="select-item selected"]';
    PlatformDropDownAndroidOptionSelected='//span[contains(text(),"Android")]/ancestor::label[@class="select-item selected"]';
    PlatformDropDownChromeOSOptionSelected='//span[contains(text(),"Chrome OS")]/ancestor::label[@class="select-item selected"]';
    LowerCPMTitle="//label[normalize-space()='Lower CPM']";
    UpperCPMTittle="//label[normalize-space()='Upper CPM']";
    LowerCPMInputBox="//input[@placeholder='Example: $6.92']";
    UpperCPMInputBox="//input[@placeholder='Example: $20.5']";
    ValidationMessageForCPM="//p[@class='d-block text-input-error-label small']";
    CountryTitle="//label[normalize-space()='Countries']";
    CountryDropDown="//body[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[6]/div[1]/div[1]/div[1]";
    CountryDropDownSelectAllOption="//span[normalize-space()='Select All']";
    CountryDropDownAfghanistanOption="//span[normalize-space()='Afghanistan']";
    CountryDropDownAmericanSamoaOption="//span[normalize-space()='American Samoa']";
    CountryDropDownSelectAllOptionSelected='//span[contains(text(),"Select All")]/ancestor::label[@class="select-item selected"]';
    CountryDropDownAfghanistanOptionSelected='//span[contains(text(),"Afghanistan")]/ancestor::label[@class="select-item selected"]';
    CountryDropDownAlbaniaOptionSelected='//span[contains(text(),"Albania")]/ancestor::label[@class="select-item selected"]';
    CountryDropDownAmericanSamoaOptionSelected='//span[contains(text(),"American Samoa")]/ancestor::label[@class="select-item selected"]';
    StateTitle="//label[normalize-space()='States']";
    StateDropDown="//body[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[7]/div[1]/div[1]/div[1]/div[1]";
    StateDropDownSelectAllOption="//span[normalize-space()='Select All']";
    StateDropDownBadakhshanOption="//span[normalize-space()='Badakhshan']";
    StateDropDownBamyanOption="//span[normalize-space()='Bamyan']";
    StateDropDownSelectAllOptionSelected='//span[contains(text(),"Select All")]/ancestor::label[@class="select-item selected"]';
    StateDropDownBadakhshanOptionSelected='//span[contains(text(),"Badakhshan")]/ancestor::label[@class="select-item selected"]';
    StateDropDownBaghlanOptionSelected='//span[contains(text(),"Baghlan")]/ancestor::label[@class="select-item selected"]';
    StateDropDownBamyanOptionSelected='//span[contains(text(),"Bamyan")]/ancestor::label[@class="select-item selected"]';
    CitiesTitle="//label[normalize-space()='Cities']";
    CitiesDropdown="//div[@class='filter__sidebar__filed d-flex flex-column react-select-dropdown']//div[@class='dropdown-container']";
    CitiesDropDownSelectAllOption="//span[normalize-space()='Select All']";
    CitiesDropDownAshkāshamOption="//span[normalize-space()='Ashkāsham']";
    CitiesDropDownRāghistānOption="//span[normalize-space()='Rāghistān']";
    CitiesDropDownSelectAllOptionSelected='//span[contains(text(),"Select All")]/ancestor::label[@class="select-item selected"]';
    CitiesDropDownAshkāshamOptionSelected='//span[contains(text(),"Ashkāsham")]/ancestor::label[@class="select-item selected"]';
    CitiesDropDownJurmOptionSelected='//span[contains(text(),"Jurm")]/ancestor::label[@class="select-item selected"]';
    CitiesDropDownRāghistānOptionSelected='//span[contains(text(),"Rāghistān")]/ancestor::label[@class="select-item selected"]';
    SubmitButton="//button[normalize-space()='Submit']";
  }
  