module.exports = class DSP_User {


  EmailTextField = '//input[@name="email"]';
  LoginButton = '//button[@type="submit"]';
  PasswordTextField = '//input[@name="password"]';
  ProfileName = '//div[@class="tour-settings dropdown"]';
  ProfileImage = '//button[@class="button button-secondary d-flex justify-content-end align-items-center dropdown-toggle btn btn-primary"]//img';
  AddNewButton = '(//button[@class="button button-primary tour-addnew-dsp" and contains(text(),"Add New")])[1]';
  SettingsTab = '//a[@class="dropdown-item" and contains(text(),"Settings")]';
  TitleProfile = '//h2[contains(text(),"Profile Settings")]'
  Title_Select_Header_Bidding_Connector = '(//div[@class="tab-content"])[4]//h3';
  InpuOfNewPassword = '//input[@placeholder="Enter new Password"]';
  InpuOfConfirmPassword = '//input[@placeholder="Confirm Password"]';
  Header_Bidding_Tab = '//a[@class="nav-item nav-link" and contains(text(),"Header Bidding")]';
  ChangedProfileName = '//div[@class="col header__right__menu__name"]//p';
  Data_Not_found = '//h3[contains(text(),"Data not found")]'
  LinkOfPasswordChange = '//label[contains(text(),"Password")]//parent::div//p[@class="profile__main__link fw-lighter" and contains(text(),"Change")]';
  DisabledSetPasswordButton = '//button[@class="button button-full button-disabled undefined"]';
  EnabledSetPasswordButton = '//button[@class="button button-full button-primary undefined"]';
  ToasterPasswordSuccessfullyChanged = '//div[@class="Toastify__toast Toastify__toast-theme--light Toastify__toast--success"]';
  LogoutTab = '//a[@class="dropdown-item" and contains(text(),"Logout")]';
  SourcesOnDashboard = '//div[@class="newsidebar"]//h3[contains(text(),"Sources")]';
  Finance_Tab = '//a[@data-rb-event-key="finance"]'
  Title_Total_Dolar = "//h2[normalize-space()='Total: $']";
  FinanceButton = '//button[@class="button button-secondary" and contains(text(),"Finance")]';
  First_On_Hover = '//div[@class="modal-body px-3 pb-3 pt-0 light-shadow"]//div[@class="my-1 bidder-item"][1]';
  RTBEndPointIntegrationActive = '//a[@class="nav-item nav-link active" and contains(text(),"RTB Endpoint Integration")]';
  LabelIntegrationName = '(//label[contains(text(),"Integration Name")])[1]';
  ToggleOfAllTraffic = '((//div[@class="align-items-center d-flex switch"])[1]//div)[1]';
  ToggleOfAllTraffic_on_VAST_URL = '((//label[contains(text(),"All Traffic")])[3]//parent::div//div)[1]';
  SelectedRTBRadioButtonText = '//div[@class="fade tab-pane active show"]//div[@class="radio-o radio-o-selected"]//parent::div//parent::div//p'
  UnselectedRTBRadioButtonofVASTURL = '((//div[@class="radio radio-mini"])[2]//div[@class="radio-col"])[1]'
  InputIntegrationName = "//div[@class='fade tab-pane active show']//input[@placeholder='Enter Integration Name']";
  Textarea_Of_VAST_URl = '//div[@class="fade tab-pane active show"]//textarea';
  InputIntegrationName2 = '//label[contains(text(),"Integration Name")]//parent::div//input[@placeholder="Enter Integration Name"]';
  SelectedRTBRadioText = '(//div[@class="radio radio-selected radio-mini"]//p)[1]';
  SelectedRTBRadioButton = '(//div[@class="radio radio-selected radio-mini"])[1]';
  UnselectedRTBRadioButton = '(//div[@class="radio radio-mini"])[1]';
  UnselectedRTBRadioText = '(//div[@class="radio radio-mini"]//p)[1]';
  LabelMinFloorPriceonModal = '//div[@class="form-group"]//label[contains(text(),"Min Floor Price")]';
  LabelMaxFloorPriceonModal = '//div[@class="form-group"]//label[contains(text(),"Max Floor Price")]';
  InputOfMaxFloorPrice = '//div[@class="form-group"]//label[contains(text(),"Max Floor Price")]//parent::div//input';
  InputOfMinFloorPrice = '//div[@class="form-group"]//label[contains(text(),"Min Floor Price")]//parent::div//input';
  ErrorOfEnterYourIntegrationName = '//div[@class="text-input-error-label small" and contains(text(),"Enter your Integration Name")]';
  ErrorOf_Select_Device_Type = '//div[@class="text-input-error-label small" and contains(text(),"Select Device Type")]';
  ErrorOfEnterYourIntegrationNameOnVastURL = '//div[@class="text-input-error-label small" and contains(text(),"Enter your integration name")]';
  ErrorOfEnterYourRTBEndPointURL = '//div[@class="text-input-error-label small" and contains(text(),"Enter your RTB End Point")]';
  ErrorOfEnterYourMinFloorPrice = '//div[@class="text-input-error-label small" and contains(text(),"Enter your Min Floor Price")]';
  ErrorOfEnterYourMaxFloorPrice = '//div[@class="text-input-error-label small" and contains(text(),"Enter your Max Floor Price")]';
  ErrorOfEnterYourVASTURL = '//div[@class="text-input-error-label small" and contains(text(),"Enter your VAST URL")]'
  ErrorOfMaxMustBeMoreThanMin = '//div[@class="text-input-error-label small" and contains(text(),"Max must be more than min")]';
  LableDeviceType = '(//form//label[contains(text(),"Device Type")])[1]';
  LabelAllOfCheckbox = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"All")])[1]';
  CheckboxOfAll = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"All")])[1]//parent::div//input';
  LabelMobile_TabletOfCheckbox = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Mobile/Tablet")])[1]';
  CheckboxOfMobile_Tablet = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Mobile/Tablet")])[1]//parent::div//input';
  Add_Button = '(//div[@class="align-items-center d-flex justify-content-between"]//button[contains(text(),"Add")])[1]';
  LabelPersonal_ComputerOfCheckbox = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Personal Computer")])[1]';
  CheckboxOfPersonal_Computer = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Personal Computer")])[1]//parent::div//input';
  LabelConnected_Tv_OfCheckbox = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Connected TV")])[1]';
  CheckboxOfConnected_Tv = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Connected TV")])[1]//parent::div//input';
  Label_Phone_OfCheckbox = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Phone")])[1]';
  CheckboxOf_Phone = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Phone")])[1]//parent::div//input';
  Label_Tablet_OfCheckbox = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Tablet")])[1]';
  CheckboxOf_Tablet = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Tablet")])[1]//parent::div//input';
  Label_Connected_Device_OfCheckbox = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Connected Device")])[1]';
  CheckboxOf_Connected_Device = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Connected Device")])[1]//parent::div//input';
  Label_Set_Top_Box_OfCheckbox = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Set Top Box")])[1]';
  CheckboxOf_Set_Top_Box = '(//label[@class="mb-0 ms-2 text-black label pt-1" and contains(text(),"Set Top Box")])[1]//parent::div//input';
  Input_RTB_End_Point = "//input[@name='integrationEndPoint']";
  Close_Button = '(//button[@class="button button-secondary undefined"])[1]';
  Close_Button2 = '(//div[@class="modal-content"]//button[contains(text(),"Close")])[2]';
  Disabled_Test_Integration_button = '//button[@class="button button-large button-primary float-end button-disabled"]';
  Enabled_Test_Integration_button = '(//button[@class="button button-large button-primary float-end"])[1]';
  ErrorToaster = '//div[@class="Toastify__toast Toastify__toast-theme--light Toastify__toast--error"]';
  SuccessToaster = '//div[@class="Toastify__toast Toastify__toast-theme--light Toastify__toast--success"]';
  Error_Toaster_Of_Header_Biiddig = '//div[@class="Toastify__toast Toastify__toast-theme--light Toastify__toast--error"]';
  RTBVersionOnEndPoint = '(//div[@class="card card-selected"]//div[@class="card-expanded"]//div[@class="card-col"])[1]//b//label';
  PriceOfMinFloorPriceOnEndPoint = '(//div[@class="card card-selected"]//div[@class="card-expanded"]//div[@class="card-col"])[2]//b//label';
  PriceOfMaxFloorPriceOnEndPoint = '(//div[@class="card card-selected"]//div[@class="card-expanded"]//div[@class="card-col"])[3]//b//label';
  PendingLabel = '//div[@class="card card-selected"]//label[contains(text(),"Pending")]';
  SearchIcon = '(//div[@class="sidebar-row"]//div[@class="sidebar-col"]//*[@id="search-btn"])[1]';
  Input_SearchKeywords = '//input[@placeholder="Search Keywords.."]';
  DetailsButton = "(//div[@class='align-items-center d-flex gap-2']//*[name()='svg'])[1]";
  EditButtonPenInDashbord = "(//div[@class='align-items-center d-flex gap-2']//*[name()='svg'])[2]";
  EndPointName = '//input[@placeholder="Enter Integration Name"]';
  RTBURL = '//input[@placeholder="Enter RTB Endpoint URL"]';
  EditButtoninForm = "//button[normalize-space()='Edit']";
  UpdateButton = '//button[@class="button button-large button-primary float-end"]';
  UpdateSuccessToaster = "//div[@role='alert']";
  ErrorOfEnterYourValidUrl = '//div[@class="text-input-error-label small" and contains(text(),"Enter Valid Url")]';
  SpendigLabel = '//span[@class="header__right__wrap__box__lable"]';
  SpendingValue = '//span[@class="header__right__wrap__box__value"]';
  SourcesTitle = '//div[@class="sidebar-col" and ./h3[contains(text(),"Sources")]]';
  InputOfFloorPrice = '//input[@name="integrationCPM"]';
  Calendar = '//div[@class="calendar__wrap"]';
  PerformanceButton = '//a[@data-rb-event-key="performance"]';
  TrafficButton = '//a[@data-rb-event-key="traffic"]';
  HeaderOfDashboard = '//div[@class="header"]';
  LogoOnDashboard = '//div[@class="header"]//a//img[@alt="infy-tv-logo"]';
  ProfileBoxOnHeader = '//img[@class="rounded-circle ms-2"]/parent::button';
  NotificationIcon = '//div[@class="position-relative"]';
  HelpIcon = '//div[@class="position-relative"]//parent::div//*[@class="svg-icon"]';
  FixFloorRadioButton = '(//p[contains(text(),"Fix Floor")])[1]//parent::div//parent::div[@class="radio-row"]';
  Error_Of_Enter_Your_Floor_Price = '//div[contains(text(),"Enter your Floor Price")]';
  LabelFloorPriceofInputBox = "//label[normalize-space()='Floor Price']";
  Endpoint_on_Created_Endpoint = '((//div[@class="card card-selected"]//h6))[1]'
  Floor_Price_Value = "//div[@class='card card-selected']//label[normalize-space()='Floor']//parent::div//b//label";
  DetailsIcon = '(//div[@class="align-items-center d-flex gap-2"]//*[contains(text(),"Details")]//parent::*)[1]';
  TitleEndpointDetails = '//div[@class="modal-header px-3"]//h3';
  Close_Button_On_Modal = "(//button[normalize-space()='Close'])[1]";
  EndPointNameOnModal = "//input[@placeholder='Enter Integration Name']";
  EdpointNameOfCreatedEndPoint = '(//div[@class="card card-selected"]//h6)[1]';
  FloorPriceOnModal = '//input[@name="integrationCPM"]';
  RTBEndPointOnModal = "//input[@placeholder='Enter RTB Endpoint URL']";
  DeviceTypes_Mobile_Tablet_OnModal = '(//div[@class="d-flex flex-wrap gap-3"]//label)[2]';
  DeviceTypes_Personal_Computer_OnModal = '(//div[@class="d-flex flex-wrap gap-3"]//label)[3]';
  DeviceTypes_Connected_TV_OnModal = '(//div[@class="d-flex flex-wrap gap-3"]//label)[4]';
  DeviceTypes_Phone_OnModal = '(//div[@class="d-flex flex-wrap gap-3"]//label)[5]';
  DeviceTypes_Tablet_OnModal = '(//div[@class="d-flex flex-wrap gap-3"]//label)[6]';
  DeviceTypes_Connected_Device_OnModal = '(//div[@class="d-flex flex-wrap gap-3"]//label)[7]';
  DeviceTypes_Set_Top_Box_OnModal = '(//div[@class="d-flex flex-wrap gap-3"]//label)[8]';
  TitleUpdateRTBEndPoint = '//div[@class="modal-header px-3"]//h3';
  Update_Button = '// button[@type="submit" and contains(text(),"Update")]';
  Updated_Successfully_Toaster = '//div[@class="Toastify__toast Toastify__toast-theme--light Toastify__toast--success"]';
  EditIcon = '(//div[@class="align-items-center d-flex gap-2"]//*[contains(text(),"Edit")]//parent::*)[1]';
  ProfileImageIcon = '(//div[@class="upload-file"])[1]';
  ProfileFirstNameInputBox = '//input[@name="profileFirstName"]';
  ProfileLastNameInputBox = '//input[@name="profileLastName"]';
  LabelFirstName = '//label[contains(text(),"First Name")]';
  InputFirstName = '//input[@name="profileFirstName"]';
  LabelLastName = '//label[contains(text(),"Last Name")]';
  InputLastName = '//input[@name="profileLastName"]';
  InputFirstNameOnModal = '//input[@name="firstName"]';
  InputLastNameOnModal = '//input[@name="lastName"]';
  UserEmail = '//label[contains(text(),"Email")]//parent::div[@style="width: fit-content;"]//p//b';
  InviteButtonOnDashboard = '(//button[contains(text(),"Invite")])[1]';

  SelectedRedioButtonOfPublisher = '//p[contains(text(),"Publisher")]//parent::div//parent::div//div[@class="radio-o radio-o-selected"]';
  MSGInvitationSuccessfully = '//p[contains(text(),"Invitation has sent successfully")]';
  CreateTagTitle = '//h3[@class="mb-4"]';
  DSPButton = '//div[@class="radio radio-mini"]';
  CustomerPassword = '//input[@name="password"]';
  CustomerEmail = '//input[@name="email"]';
  CompanyName = '//input[@name="name"]';
  InviteButton = '(//button[contains(text(),"Invite")])[2]';
  CustomerCreated = '//h2[contains(text(),"Customer Created")]';
  DoneButtonOnModal = '(//button[contains(text(),"Done")])[1]';
  Logout = '//a[contains(text(),"Logout")]';
  TitleLetsTakeATour = '//div[@class="modal-content"]//h2';
  NextButtonOnModal = '//div[@class="modal-content"]//button[contains(text(),"Next")]';
  DoneButtonOfModal ='//div[@class="modal-content"]//button[contains(text(),"Done")]';
  FloaterBody = '//div[@class="__floater__body"]';
  TitleOfFloater = '//DIV[@class="__floater__body"]//div//p[1]';
  DescriptionOfFloater = '//DIV[@class="__floater__body"]//div//p[2]';
  MSA_Bypass_Label = '(//div[@class="col-3"]//label[contains(text(),"MSA Bypass")])[1]'
  MSA_Checkbox = '//input[@name="msa"]';
  NextButtonOnFloater = '//DIV[@class="__floater__body"]//button[contains(text(),"Next")]';
  LetsGoButton = "//DIV[@class='__floater__body']//button[contains(text(),\"Let's Go\")]";
  SelectHeaderBiddingConnectorTitle = "//h3[normalize-space()='Select Header Bidding Connector']";
  MSA_Checkbox_Checked = '//label[contains(text(),"MSA Execute")]//parent::div//input[@class="form-check-input" and @checked]';
  SearchBox = '//input[@class="text-input-mini mb-4"]';
  HeaderBidderConnectorListFirstConnector = '//div[@class="align-items-center d-flex"]';
  HeaderBidderConnectorListFirstConnectorframe = '//div[@class="modal-body px-3 pb-3 pt-0 light-shadow"]//div[@class="my-1 bidder-item"][1]';
  Addbutton = '(//div[@class="my-1 bidder-item"])[1]//button[@class="button button-primary undefined" and contains(text(),"Add")]';
  legend = "//legend";
  Input_Integration_Name = '//input[@label="integrationName"]';
  Input_Product_ID = '//input[@id="root_productId"]';
  Input_Product_ID = '//input[@label="productId"]';
  Input_Site_ID = '//input[@label="siteId"]';
  Input_Zone_ID = '//input[@label="zoneId"]';
  Back_Button = '//button[contains(text(),"Back")]';
  Test_Integration_Button = '(//button[contains(text(),"Test Integration")])[2]';
  Errorof_Integration_Name = '//label[contains(text(),"integrationName")]//parent::div//li[contains(text(),"is a required property")]'
  Errorof_Product_Id = '//label[contains(text(),"productId")]//parent::div//li[contains(text(),"is a required property")]'
  Errorof_Site_Id = '//label[contains(text(),"siteId")]//parent::div//li[contains(text(),"is a required property")]'
  SearchButtton = '(//div[@class="sidebar-col"]//div)[2]';
  SearchInput = '//input[@id="search-bar"]';
  Welcome_MSG = '//div[@class="intercom-1hu6sk e141za3z4"]';
  Clear_Button = '//button[contains(text(),"Clear")]';
  Vast_XMLLink = "//a[contains(text(),'VAST XML')]";
  Vast_URL_Tab = '//a[@class="nav-item nav-link" and contains(text(),"VAST URL")]';
  CloseButton = '//button[contains(text(),"Add VAST Xml")]//parent::div//button[@type="button" and contains(text(),"Close")]';
  Close_Button_Of_VAST_URl = '//button[ contains(text(),"Check Macros")]//parent::div//button[contains(text(),"Close")]';
  AddVASTXmlButton = "//button[contains(text(),'Add VAST Xml')]";
  Check_Macros_Button = '//button[ contains(text(),"Check Macros")]'
  ValidationmessageOFIntegrationNameField = "//div[@class='text-input-error-label small' and contains(text(),'Integration')]";
  ValidationmessageOFDeviceType = "//div[@class='text-input-error-label small' and contains(text(),'Select')]";
  ValidationmessageOFVastXML = "//div[@class='text-input-error-label small' and contains(text(),'VAST')]";
  VastXmlIntegrationName = '(//input[@name="integrationName"])[2]';
  VastXmlCheckboxAll = '(//div[@class="d-flex flex-wrap gap-3"]//input[@type="checkbox"])[9]';
  ChekboxMobileTablet = "//div[@class='fade tab-pane active show']//input[@name='dt1']";
  ChekboxPersonalComputer = "//div[@class='fade tab-pane active show']//input[@name='dt2']";
  ChekboxConnectedTv = "//div[@class='fade tab-pane active show']//input[@name='dt3']";
  ChekboxPhone = "//div[@class='fade tab-pane active show']//input[@name='dt4']";
  ChekboxTablet = "//div[@class='fade tab-pane active show']//input[@name='dt5']";
  ChekboxConnectedDevice = "//div[@class='fade tab-pane active show']//input[@name='dt6']";
  ChekboxSetTopBox = "//div[@class='fade tab-pane active show']//input[@name='dt7']";
  EnableToggleButton = "//div[@class='fade tab-pane active show']//form[@class='rtb-form disable']//div[@class='modal-body p-3']//div[@class='row mb-3 mt-1']//div[@class='col-auto']//div[@class='align-items-center d-flex switch']//div//div[@class='react-switch-handle']";
  RadioButtonFixFloorNotSelected = "//div[@class='fade tab-pane active show']//div[@class='radio-o']";
  RadioButtonFixFloorSelected = "//div[@class='fade tab-pane active show']//div[@class='radio-o-o']";
  MinFloorPriceInput = '//input[@name="integrationMinCPM"]';
  MaxFloorPriceInput = '//input[@name="integrationMaxCPM"]';
  ValidationmessageOFMaxandminPrice = '//div[@class="text-input-error-label small" and contains(text(),"Max")]';
  Floorpricetitle = "//label[normalize-space()='Floor Price']";
  FloorPriceInput = "//input[@name='integrationCPM']";
  ValidationmessageOFFloorPrice = "//div[@class='text-input-error-label small' and contains(text(),'Min Floor Price')]";

}
